Var_Browser_type = 'chrome'
Var_URL = 'https://eng-svt.systechcloud.net/Systech360/#/'
Var_Username = 'ruleuser'
Var_Password = 'Test@101'
#Var_Username = 'Dinesh'
#Var_Password = 'Estuate@123'
Var_Title = 'Systech360'
Var_Class_Attr_Val = 'tab-selected'
WINDOW_WIDTH = '1366'
WINDOW_HEIGHT = '768'

Var_First_Name = 'Dinesh'
Var_Last_Name = 'Kumar'
Var_Email_ID = 'dinesh.kumar@estuate.com'
Var_Phone_Number = '1234567890'
Var_Company_Name = 'Test'
Var_Job_Title = 'Test'
Var_Street_Address = 'Test'
Var_Addition_Address = 'Test'
Var_City = 'Test'
Var_State = 'Test'
Var_Country = 'Test'
Var_Serial_Number = 'Test1234'
Var_Description = 'Testing Contact Support Module'
Var_SuccsMsg = 'SEC000235S'

Var_Artifact_Name = 'Test'

Var_ExpectedNumOfCharts = '6'
Var_ExpectedNumOfColumns = '7'

Var_Solution_Name = 'Systech360'
Var_Version_name = '8.3'
Var_Language_Name = 'English'
Var_Topic = 'Server'
Var_ItemName = 'patch'

Var_SceneName1 = 'ERjPBpZoAs'
Var_Expected_Download_File_Name = 'UniSeries 8.5.4 Guardian Patch'