Browser_Type				=	'chrome'

URL							=	'https://eng-svt.systechcloud.net/Systech360/#/'
SEC_URL						=	'https://eng-svt.systechcloud.net/Systech360/#/'
CLD_URL						=	'http://54.211.70.146:8008/UniCloud/#/login'

CLD_Username				=	'Automation'
CLD_Password				=	'Test!234'
SEC_Username				=	'AdminUser1'
SEC_Password				=	'Test@101'

Title						=	'UniSecure'
Artifact_Name				=	'update'
Succes_Mes					=	'Thank you for your feedback'
Solution_Name				=	'UniSecure'
Version_name				=	'8.5.0'
Language_Name				=	'English'
Topic						=	'Export'
Attribute_Name				=	'class'
Expected_Value				=	'tab-selected'
WINDOW_WIDTH				=	'1920'
WINDOW_HEIGHT				=	'1080'
CLD_UniSphere_Index			=	'2'
CLD_Subs_Video_Index		=	'5'
CLD_Sys_Resp_Index			=	'0'
CLD_Tier_Name				=	'Tier 1'
ENG_SVT_CUST_ID				=	'0100000003'
